Liebe $Name_Mutter, lieber $Name_Vater,


der aktuelle Elterndienstplan ist unter folgendem Link zu finden:

$SystemUrl/?PW=$Passwort

Dazu noch einige Erklärungen:
- Verpflichtende Elterndienste sind in gelber Farbe gekennzeichnet.
- Elterndienste vormittags sind von 09:00 bis 13:00 Uhr zu leisten.
- Elterndienste nachmittags sind montags bis donnerstags von 15:00 bis 17:30 Uhr zu leisten, freitags von 15:00 bis 16:00 Uhr.
- Im Anhang sind Kalendereinträge für alle eure Termine. Ihr könnt eure bevorzugte Kalendar App dazu benutzen.
- Falls ihr einen Elterndienst oder eine Bereitschaft nicht wahrnehmen könnt, sucht euch bitte selbst einen Tauschpartner, anderenfalls müsst ihr die Kosten für eine Aushilfe übernehmen. Informiert uns über den Tausch, wir werden dann die Liste nachpflegen.
- Wir bemühen uns, Elterndienste und Bereitschaften möglichst gerecht zu verteilen. Wenn euch also im aktuellen Elterndienstplan auffällt, dass ihr besonders viel oder besonders wenig gefordert werdet, dann werft zum Vergleich einen Blick in die Elterndienstpläne der Vormonate.
- Die Möglichkeit, Verfügbarkeiten zu bearbeiten, ist mit der Veröffentlichung des Elterndienstplans für den kommenden Monat ab sofort gesperrt.

Viele Grüße,

$SystemMainteners
