Liebe $Name_Mutter, lieber $Name_Vater,


bitte tragt eure Verfügbarkeit für Elterndienste im kommenden Monat bis $OpenedDeadline ein. Dazu steht euch folgender Link zur Verfügung:

$SystemUrl/?PW=$Passwort

Dazu noch einige Erklärungen:
- Um alle Vormittage gut abdecken zu können, bitte mindesten 2 Vormittage pro Monat Verfügbarkeit angeben.
- Urlaube sind mit grau markiert. Um neue Urlaube einzutragen bzw editieren, bitte benutzen den Link $SystemUrl/holidays?PW=$Passwort
- Es ist ein Kalender zu sehen, in dem Verfügbarkeiten in grün und Abwesenheiten in rot dargestellt werden.
- Dabei stellt das obere Feld an einem Tag den Vormittag, das untere Feld den Nachmittag dar.
- Ihr seht die Verfügbarkeit aller Eltern, könnt aber nur eure eigene editieren.
- Zum Editieren klickt ihr einfach auf das grüne bzw. rote Feld in eurer Spalte, dieses wird daraufhin seinen Status ändern.
- Ganz oben auf der Seite findet ihr die Möglichkeit, innerhalb der freigegebenen Monate zu navigieren.
- Damit könnt ihr euch jederzeit auch schon für die kommenden Monate (derzeit bis Dezember 2018) eintragen.
- In Monaten, die für die Angabe von Verfügbarkeiten geschlossen sind, findet ihr den fertigen Elterndienstplan.

Für Anregungen und Rückfragen stehen wir euch natürlich gerne zur Verfügung.

Viele Grüße,

$SystemMainteners
